version: "3"
services:
  db: 
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    image: "mysql:5.7.22"
    ports: 
      - "3306:3306"
    volumes: 
      - "/my/own/datadir:/var/lib/mysql"
    networks:
      - ac_bridge
  api: 
    build: .
    depends_on: 
      - db
    deploy: 
      replicas: 2
      restart_policy: 
        condition: on-failure
      update_config: 
        delay: 10s
        parallelism: 1
    ports: 
      - "8000:80"
    volumes: 
      - "./logs:/usr/share/api/logs"
    networks:
      - ac_bridge
networks:
  ac_bridge:
    external: true

